package final_cdio_11.java.weight.ase;

public enum WeightState {
	ENTER_LABORANT_ID, SEND_LABORANT_NAME, 
	ENTER_PB_ID, SEND_RECEIPT_NAME, START_PB_PROD, 
	TARE_WEIGHT, PLACE_TARE_CONTAINER, REG_WEIGHT, 
	ENTER_RB_ID, FINISH_PB, WEIGHT_IDLE
}